# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-10 20:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(blank=True, max_length=50)),
                ('marca', models.CharField(blank=True, choices=[('bmw', 'BMW'), ('peugeot', 'Peugeot'), ('ford', 'Ford'), ('chevrolet', 'Chevrolet')], default='bmw', max_length=10)),
                ('precio', models.IntegerField(blank=True, default=0)),
                ('descripcion', models.TextField(blank=True, max_length=255)),
                ('imagen', models.FileField(upload_to='documents/')),
                ('fechaPublicacion', models.DateTimeField(auto_now_add=True)),
                ('resWatsonClase', models.CharField(blank=True, max_length=1000)),
                ('resWatsonScore', models.IntegerField(blank=True)),
                ('resWatsonValidacionMarca', models.IntegerField(blank=True)),
                ('resWatsonClasificacionDescripcion', models.CharField(blank=True, max_length=110)),
            ],
        ),
    ]
