# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-10 20:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='marca',
            field=models.CharField(blank=True, choices=[('bmw', 'BMW'), ('peugeot', 'Peugeot'), ('ford', 'Ford'), ('chevrolet', 'Chevrolet')], default='bmw', max_length=20),
        ),
    ]
