# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-11 17:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20171010_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='marca',
            field=models.CharField(blank=True, choices=[('bmw', 'BMW'), ('chevrolet', 'Chevrolet'), ('ford', 'Ford'), ('volkswagen', 'Chevrolet'), ('nissan', 'Nissan')], default='bmw', max_length=20),
        ),
    ]
