# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-11 17:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20171011_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='resWatsonClase',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='resWatsonClasificacionDescripcion',
            field=models.CharField(blank=True, max_length=110, null=True),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='resWatsonScore',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='resWatsonValidacionMarca',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
